### ISSUE TITLE
Member의 변수

### ISSUE THREAD

**Issue by Lee-Jiseung** [Road-to-Study/ItemWeb#2]
Member내의 member_number와 i의 차이는 뭔가요?

**Comment by YOOBINNOH** [comment]
유저마다 고유한 member_number 를 부여해야 해서 i 값을 이용해서 1씩 커지도록 했어요.
예를 들어 첫 유저는 member_number+i = 0+0=0 그 다음 유저는 member_number + i = 0+1 =1 이런 식으로요.
테스트 코드 짜보려고 했는데 회원가입 기능이 아직 미구현이라 안됐습니당

**Comment by YOOBINNOH** [comment]
네 그렇게 해도 됩니다. 그렇게 하려다가 계속 오류 뜨길래 바꿨어요
